-- ==============================================================================
-- SESI NEWS - SUPABASE DATABASE SCHEMA
-- Execute este script no SQL Editor do seu painel Supabase (https://supabase.com)
-- ==============================================================================

-- 1. Habilitar extensões necessárias
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Tabela de Notícias (articles)
CREATE TABLE IF NOT EXISTS public.articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    content TEXT NOT NULL,
    image TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Geral',
    date TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabela de Eventos e Agenda Escolar (events)
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    time TEXT NOT NULL,
    location TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Geral',
    description TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabela de Vídeos e Transmissões (videos)
CREATE TABLE IF NOT EXISTS public.videos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    is_live BOOLEAN DEFAULT false,
    category TEXT NOT NULL DEFAULT 'Geral',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabela de Administradores (admins)
CREATE TABLE IF NOT EXISTS public.admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'admin',
    password TEXT,
    is_pending BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. Habilitar Row Level Security (RLS) e Políticas de Leitura Pública
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;

-- Políticas de Leitura Pública para Notícias, Eventos e Vídeos
CREATE POLICY "Permitir leitura pública de notícias" ON public.articles
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserção e modificação de notícias via backend" ON public.articles
    FOR ALL USING (true);

CREATE POLICY "Permitir leitura pública de eventos" ON public.events
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserção e modificação de eventos via backend" ON public.events
    FOR ALL USING (true);

CREATE POLICY "Permitir leitura pública de vídeos" ON public.videos
    FOR SELECT USING (true);

CREATE POLICY "Permitir inserção e modificação de vídeos via backend" ON public.videos
    FOR ALL USING (true);

CREATE POLICY "Gerenciamento de admins via backend" ON public.admins
    FOR ALL USING (true);

-- 7. Dados Iniciais de Exemplo (Seed Data)
INSERT INTO public.articles (title, summary, content, image, category, date)
VALUES
  (
    'Alunos do SESI vencem etapa regional de Robótica com projeto inovador',
    'Equipe desenvolveu robô autônomo com foco em sustentabilidade e eficiência energética, conquistando o 1º lugar.',
    'A equipe de robótica da nossa escola alcançou o primeiro lugar na etapa regional da First Lego League (FLL). Com o tema sustentabilidade, os alunos desenvolveram um robô totalmente autônomo capaz de realizar tarefas complexas com gasto mínimo de energia.\n\n"Foi um trabalho em equipe incrível de mais de seis meses de dedicação", comentou o orientador do projeto. A equipe agora se prepara para representar a instituição na etapa nacional em Brasília.',
    'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=1200',
    'Tecnologia',
    '20 de Março, 2024'
  ),
  (
    'Festival de Talentos SESI reúne estudantes em celebração de arte e música',
    'Apresentações de dança, canto e teatro movimentaram o teatro escolar durante três dias de evento.',
    'O Festival Cultural de 2024 foi um sucesso absoluto. Mais de 40 apresentações artísticas divididas em categorias como música autoral, dança contemporânea e peças teatrais curtas encantaram pais, alunos e professores.',
    'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&q=80&w=800',
    'Cultura',
    '18 de Março, 2024'
  ),
  (
    'Inscrições abertas para a Feira de Ciências e Tecnologia 2024',
    'Estudantes de todas as turmas podem inscrever projetos interdisciplinares até o final deste mês.',
    'A Feira de Ciências deste ano traz o tema "Inteligência Artificial e o Futuro da Educação". As inscrições podem ser feitas diretamente com os professores orientadores de cada área.',
    'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&q=80&w=800',
    'Educação',
    '15 de Março, 2024'
  ),
  (
    'Time de Futsal do SESI conquista vaga na grande final dos Jogos Escolares',
    'Após vitória emocionante nos pênaltis, a equipe garante presença na disputa pelo título estadual.',
    'Num jogo acirrado contra a equipe municipal, nossos atletas demonstraram garra e espírito de equipe, vencendo a semifinal e garantindo a vaga para a grande final no próximo sábado.',
    'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800',
    'Esportes',
    '12 de Março, 2024'
  );

INSERT INTO public.events (title, date, time, location, category, description)
VALUES
  (
    'Reunião de Pais e Mestres - 1º Bimestre',
    '2024-04-10',
    '19:00',
    'Auditório Principal',
    'Institucional',
    'Encontro para discussão do rendimento pedagógico e metas do bimestre.'
  ),
  (
    'Feira de Ciências e Tecnologia 2024',
    '2024-04-25',
    '08:00 às 17:00',
    'Ginásio Poliesportivo',
    'Educação',
    'Exposição dos projetos dos alunos de todas as séries.'
  ),
  (
    'Final dos Jogos Escolares Interclasses',
    '2024-05-04',
    '09:00',
    'Quadra Coberta',
    'Esportes',
    'Disputa final dos torneios de Futsal, Vôlei e Queimada.'
  ),
  (
    'Palestra: Profissões do Futuro & IA',
    '2024-05-18',
    '14:00',
    'Sala Multimídia',
    'Carreira',
    'Palestra especial para alunos do Ensino Médio com especialistas convidados.'
  );

INSERT INTO public.videos (title, url, is_live, category)
VALUES
  (
    'Transmissão ao Vivo: Cerimônia de Abertura dos Jogos SESI 2024',
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    true,
    'Ao Vivo'
  ),
  (
    'Destaques da Feira de Robótica e Sustentabilidade',
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    false,
    'Tecnologia'
  ),
  (
    'Melhores Momentos do Festival de Música e Dança',
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    false,
    'Cultura'
  );

INSERT INTO public.admins (email, role, password, is_pending)
VALUES
  ('admin@sesi.org.br', 'super_admin', 'admin123', false),
  ('coordenacao@sesi.org.br', 'admin', NULL, true);
